export const roles = [
  {
    id: 1,
    name: "ADMIN",
  },
  {
    id: 2,
    name: "SUPERADMIN",
  },
];

export const apps = [
  {
    id: 1,
    name: "Admin",
    origin: "admin-origin",
    supportedRoles: roles,
  },
  {
    id: 2,
    name: "User",
    origin: "admin-origin",
    supportedRoles: [
      {
        id: 2,
        name: "USER",
      },
    ],
  },
];

export const allUsers = [
  {
    id: "user-1",
    email: "john@dzangolab.com",
    givenName: "John",
    roles: ["USER"],
    surname: "Doe",
    username: "johndoe",
    isActiveUser: true,
    invitedBy: null,
    signedUpAt: "2023-08-10T08:00:00Z",
    disabled: false,
  },
  {
    id: "invitation-123",
    email: "jane@dzangolab.com",
    givenName: "Jane",
    roles: ["ADMIN"],
    surname: "Smith",
    username: "janesmith",
    isActiveUser: false,
    invitedBy: {
      id: "user-2",
      email: "admin@dzangolab.com",
      givenName: "Admin",
      roles: ["USER"],
      surname: "User",
      username: "admin",
      isActiveUser: true,
    },
    disabled: true,
  },
  {
    id: "user-3",
    email: "alice@dzangolab.com",
    givenName: "Alice",
    roles: ["USER"],
    surname: "Johnson",
    username: "alicej",
    isActiveUser: true,
    invitedBy: null,
    signedUpAt: "2023-08-08T10:30:00Z",
    disabled: false,
  },
  {
    id: "invitation-456",
    email: "bob@dzangolab.com",
    givenName: "Bob",
    roles: ["ADMIN"],
    surname: "Williams",
    username: "bobw",
    isActiveUser: false,
    disabled: false,
    invitedBy: {
      id: "user-4",
      email: "charlie@dzangolab.com",
      givenName: "Charlie",
      roles: ["USER"],
      surname: "Brown",
      username: "charlieb",
      isActiveUser: true,
    },
  },
  {
    id: "user-6",
    email: "george@dzangolab.com",
    givenName: "george",
    roles: ["USER"],
    surname: "williams",
    username: "george",
    isActiveUser: true,
    invitedBy: null,
    signedUpAt: "2023-10-10T08:00:00Z",
    disabled: true,
  },
];

export const invitations = [
  {
    id: 456,
    appId: 9,
    createdAt: 1_704_456_459_043,
    expiresAt: 1_707_048_459_043,
    email: "bob@dzangolab.com",
    givenName: "Bob",
    payload: null,
    roles: ["ADMIN"],
    surname: "Williams",
    username: "bobw",
    isActiveUser: false,
    disabled: false,
    invitedById: "user-4",
    revokedAt: 1_704_446_459_043,
    acceptedAt: null,
    role: "USER",
    updatedAt: 1_703_827_894_297,
    invitedBy: {
      id: "user-4",
      email: "charlie@dzangolab.com",
      givenName: "Charlie",
      roles: ["USER"],
      surname: "Brown",
      username: "charlieb",
      isActiveUser: true,
    },
  },
  {
    id: 123,
    appId: 10,
    createdAt: 1_705_456_459_043,
    expiresAt: 1_707_048_459_043,
    email: "jane@dzangolab.com",
    givenName: "Jane",
    payload: null,
    roles: ["ADMIN"],
    surname: "Smith",
    username: "janesmith",
    isActiveUser: false,
    invitedById: "user-2",
    revokedAt: null,
    acceptedAt: null,
    role: "USER",
    updatedAt: 1_703_827_894_297,
    invitedBy: {
      id: "user-2",
      email: "admin@dzangolab.com",
      givenName: "Admin",
      roles: ["USER"],
      surname: "User",
      username: "admin",
      isActiveUser: true,
    },
    disabled: true,
  },
  {
    id: 789,
    appId: 11,
    createdAt: 1_704_466_459_043,
    expiresAt: 1_704_466_459_043,
    payload: null,
    email: "june@dzangolab.com",
    givenName: "June",
    roles: ["ADMIN"],
    surname: "Smith",
    username: "junesmith",
    isActiveUser: false,
    invitedById: "user-8",
    revokedAt: null,
    acceptedAt: 1_704_457_459_043,
    role: "USER",
    updatedAt: 1_703_827_894_297,
    invitedBy: {
      id: "user-8",
      email: "jonny@dzangolab.com",
      givenName: "Admin",
      roles: ["USER"],
      surname: "User",
      username: "admin",
      isActiveUser: true,
    },
    disabled: true,
  },
  {
    id: 788,
    appId: 19,
    createdAt: 1_704_466_459_043,
    expiresAt: 1_704_466_459_043,
    payload: null,
    email: "june@dzangolab.com",
    givenName: "June",
    roles: ["ADMIN"],
    surname: "Smith",
    username: "junesmith",
    isActiveUser: false,
    invitedById: "user-8",
    revokedAt: null,
    acceptedAt: null,
    role: "USER",
    updatedAt: 1_703_827_894_297,
    invitedBy: {
      id: "user-8",
      email: "jonny@dzangolab.com",
      givenName: "Admin",
      roles: ["USER"],
      surname: "User",
      username: "admin",
      isActiveUser: true,
    },
    disabled: true,
  },
  {
    id: 789,
    appId: 11,
    createdAt: 1_704_466_459_043,
    expiresAt: 1_709_697_572_621,
    payload: null,
    email: "janet@dzangolab.com",
    givenName: "Janet",
    roles: ["ADMIN"],
    surname: "Smith",
    username: "janetsmith",
    isActiveUser: false,
    invitedById: "user-8",
    revokedAt: null,
    acceptedAt: null,
    role: "USER",
    updatedAt: 1_703_827_894_297,
    invitedBy: {
      id: "user-8",
      email: "jonny@dzangolab.com",
      givenName: "Admin",
      roles: ["USER"],
      surname: "User",
      username: "admin",
      isActiveUser: true,
    },
    disabled: true,
  },
];
