export const currencies = [
  { code: "AED", label: "United Arab Emirates dirham", value: "AED" },
  { code: "AFN", label: "Afghan afghani", symbol: "؋", value: "AFN" },
  { code: "ALL", label: "Albanian lek", value: "ALL" },
  { code: "AMD", label: "Armenian dram", symbol: "֏", value: "AMD" },
  {
    code: "ANG",
    label: "Netherlands Antillean guilder",
    symbol: "ƒ",
    value: "ANG",
  },
  { code: "AOA", label: "Angolan kwanza", value: "AOA" },
  { code: "ARS", label: "Argentine peso", symbol: "$", value: "ARS" },
  { code: "AUD", label: "Australian dollar", symbol: "$", value: "AUD" },
  { code: "AWG", label: "Aruban florin", symbol: "ƒ", value: "AWG" },
  { code: "AZN", label: "Azerbaijani manat", symbol: "₼", value: "AZN" },
  {
    code: "BAM",
    label: "Bosnia and Herzegovina convertible mark",
    symbol: "KM",
    value: "BAM",
  },
  { code: "BBD", label: "Barbadian dollar", symbol: "$", value: "BBD" },
  { code: "BDT", label: "Bangladeshi taka", symbol: "৳", value: "BDT" },
  { code: "BGN", label: "Bulgarian lev", symbol: "лв", value: "BGN" },
  { code: "BHD", label: "Bahraini dinar", value: "BHD" },
  { code: "BIF", label: "Burundian franc", value: "BIF" },
  { code: "BMD", label: "Bermudian dollar", symbol: "$", value: "BMD" },
  { code: "BND", label: "Brunei dollar", symbol: "$", value: "BND" },
  { code: "BOB", label: "Boliviano", symbol: "Bs.", value: "BOB" },
  { code: "BRL", label: "Brazilian real", symbol: "R$", value: "BRL" },
  { code: "BSD", label: "Bahamian dollar", symbol: "$", value: "BSD" },
  { code: "BTN", label: "Bhutanese ngultrum", symbol: "Nu.", value: "BTN" },
  { code: "BWP", label: "Botswana pula", symbol: "P", value: "BWP" },
  { code: "BYN", label: "Belarusian ruble", value: "BYN" },
  { code: "BZD", label: "Belize dollar", symbol: "BZ$", value: "BZD" },
  { code: "CAD", label: "Canadian dollar", symbol: "$", value: "CAD" },
  { code: "CDF", label: "Congolese franc", value: "CDF" },
  { code: "CHF", label: "Swiss franc", symbol: "CHF", value: "CHF" },
  { code: "CLP", label: "Chilean peso", symbol: "$", value: "CLP" },
  { code: "CNY", label: "Chinese yuan", symbol: "¥", value: "CNY" },
  { code: "COP", label: "Colombian peso", symbol: "$", value: "COP" },
  { code: "CRC", label: "Costa Rican colón", symbol: "₡", value: "CRC" },
  { code: "CUP", label: "Cuban peso", symbol: "$", value: "CUP" },
  { code: "CVE", label: "Cape Verdean escudo", value: "CVE" },
  { code: "CZK", label: "Czech koruna", symbol: "Kč", value: "CZK" },
  { code: "DJF", label: "Djiboutian franc", value: "DJF" },
  { code: "DKK", label: "Danish krone", symbol: "kr", value: "DKK" },
  { code: "DOP", label: "Dominican peso", symbol: "RD$", value: "DOP" },
  { code: "DZD", label: "Algerian dinar", value: "DZD" },
  { code: "EGP", label: "Egyptian pound", symbol: "£", value: "EGP" },
  { code: "ERN", label: "Eritrean nakfa", value: "ERN" },
  { code: "ETB", label: "Ethiopian birr", symbol: "Br", value: "ETB" },
  { code: "EUR", label: "Euro", symbol: "€", value: "EUR" },
  { code: "FJD", label: "Fijian dollar", symbol: "$", value: "FJD" },
  { code: "FKP", label: "Falkland Islands pound", symbol: "£", value: "FKP" },
  { code: "GBP", label: "British pound", symbol: "£", value: "GBP" },
  { code: "GEL", label: "Georgian lari", symbol: "₾", value: "GEL" },
  { code: "GHS", label: "Ghanaian cedi", symbol: "₵", value: "GHS" },
  { code: "GIP", label: "Gibraltar pound", symbol: "£", value: "GIP" },
  { code: "GMD", label: "Gambian dalasi", symbol: "D", value: "GMD" },
  { code: "GNF", label: "Guinean franc", symbol: "Fr", value: "GNF" },
  { code: "GTQ", label: "Guatemalan quetzal", symbol: "Q", value: "GTQ" },
  { code: "GYD", label: "Guyanese dollar", symbol: "$", value: "GYD" },
  { code: "HKD", label: "Hong Kong dollar", symbol: "$", value: "HKD" },
  { code: "HNL", label: "Honduran lempira", symbol: "L", value: "HNL" },
  { code: "HRK", label: "Croatian kuna", symbol: "kn", value: "HRK" },
  { code: "HTG", label: "Haitian gourde", symbol: "G", value: "HTG" },
  { code: "HUF", label: "Hungarian forint", symbol: "Ft", value: "HUF" },
  { code: "IDR", label: "Indonesian rupiah", symbol: "Rp", value: "IDR" },
  { code: "ILS", label: "Israeli new shekel", symbol: "₪", value: "ILS" },
  { code: "INR", label: "Indian rupee", symbol: "₹", value: "INR" },
  { code: "IQD", label: "Iraqi dinar", symbol: "ع.د", value: "IQD" },
  { code: "IRR", label: "Iranian rial", symbol: "﷼", value: "IRR" },
  { code: "ISK", label: "Icelandic króna", symbol: "kr", value: "ISK" },
  { code: "JMD", label: "Jamaican dollar", symbol: "J$", value: "JMD" },
  { code: "JOD", label: "Jordanian dinar", symbol: "د.ا", value: "JOD" },
  { code: "JPY", label: "Japanese yen", symbol: "¥", value: "JPY" },
  { code: "KES", label: "Kenyan shilling", symbol: "KSh", value: "KES" },
  { code: "KGS", label: "Kyrgyzstani som", symbol: "сом", value: "KGS" },
  { code: "KHR", label: "Cambodian riel", symbol: "៛", value: "KHR" },
  { code: "KMF", label: "Comorian franc", value: "KMF" },
  { code: "KPW", label: "North Korean won", symbol: "₩", value: "KPW" },
  { code: "KRW", label: "South Korean won", symbol: "₩", value: "KRW" },
  { code: "KWD", label: "Kuwaiti dinar", symbol: "د.ك", value: "KWD" },
  { code: "KYD", label: "Cayman Islands dollar", symbol: "$", value: "KYD" },
  { code: "KZT", label: "Kazakhstani tenge", symbol: "₸", value: "KZT" },
  { code: "LAK", label: "Lao kip", symbol: "₭", value: "LAK" },
  { code: "LBP", label: "Lebanese pound", symbol: "ل.ل", value: "LBP" },
  { code: "LKR", label: "Sri Lankan rupee", symbol: "Rs", value: "LKR" },
  { code: "LSL", label: "Lesotho loti", value: "LSL" },
  { code: "LYD", label: "Libyan dinar", value: "LYD" },
  { code: "MAD", label: "Moroccan dirham", symbol: "د.م.", value: "MAD" },
  { code: "MDL", label: "Moldovan leu", symbol: "L", value: "MDL" },
  { code: "MGA", label: "Malagasy ariary", symbol: "Ar", value: "MGA" },
  { code: "MKD", label: "Macedonian denar", symbol: "ден", value: "MKD" },
  { code: "MMK", label: "Myanma kyat", symbol: "Ks", value: "MMK" },
  { code: "MNT", label: "Mongolian tögrög", symbol: "₮", value: "MNT" },
  { code: "MOP", label: "Macanese pataca", symbol: "MOP$", value: "MOP" },
  { code: "MRU", label: "Mauritanian ouguiya", symbol: "UM", value: "MRU" },
  { code: "MUR", label: "Mauritian rupee", symbol: "₨", value: "MUR" },
  { code: "MVR", label: "Maldivian rufiyaa", symbol: "ރ.", value: "MVR" },
  { code: "MWK", label: "Malawian kwacha", symbol: "MK", value: "MWK" },
  { code: "MXN", label: "Mexican peso", symbol: "Mex$", value: "MXN" },
  { code: "MYR", label: "Malaysian ringgit", symbol: "RM", value: "MYR" },
  { code: "MZN", label: "Mozambican metical", symbol: "MTn", value: "MZN" },
  { code: "NAD", label: "Namibian dollar", symbol: "$", value: "NAD" },
  { code: "NGN", label: "Nigerian naira", symbol: "₦", value: "NGN" },
  { code: "NIO", label: "Nicaraguan córdoba", symbol: "C$", value: "NIO" },
  { code: "NOK", label: "Norwegian krone", symbol: "kr", value: "NOK" },
  { code: "NPR", label: "Nepalese rupee", symbol: "Rs", value: "NPR" },
  { code: "NZD", label: "New Zealand dollar", symbol: "$", value: "NZD" },
];
