name: "@dzangolab/react CI"

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]
    steps:
      - uses: actions/checkout@v3
        name: Use node ${{ matrix.node-version }}

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          node-version: ${{ matrix.node-version }}
          version: 7
    
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Build packages
        run: pnpm build

      - name: Run tests
        run: pnpm test
