name: demo-cd

on:
  push:
    branches: [main]
    paths:
      - "apps/demo/**"

  workflow_dispatch:

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
        name: Use node ${{ matrix.node-version }}
        
      - uses: actions/checkout@v1

      - name: Read package.json version
        uses: dutscher/read-package-json-endpoint-actions@v1.3.37
        id: package-json-endpoint

      - name: Show version number
        run: echo "${{ steps.package-json-endpoint.outputs.endpoint }}"

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 7

      - name: Install Dependencies
        run: pnpm install

      - name: Build packages
        run: pnpm build --filter=@dzangolab/demo-app
        env:
          VITE_API_BASE_URL: "https://api.monorepo.dzangolab.org"
          VITE_APP_TITLE: 'React Demo'
          VITE_APP_VERSION: ${{ steps.package-json-endpoint.outputs.endpoint }}
          VITE_APP_BUILD: 'develop'
          VITE_APP_COPYRIGHT_HOLDER: 'Dzango Technologies Limited'
          VITE_APP_COPYRIGHT_HOLDER_URL: 'https://dzango.com'

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          clean: true
          folder: apps/demo/dist
          token: ${{ secrets.GITHUB_TOKEN }}
